// **********************************************************************
//
// Copyright (c) 2003-2018 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.7.1
//
// <auto-generated>
//
// Generated from file `IPlayerCo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//


using _System = global::System;

#pragma warning disable 1591

namespace IceCompactId
{
}

namespace Sample
{
    namespace Protocol
    {
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1715")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1722")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1724")]
        [_System.Serializable]
        public partial class RLResultRes : _System.ICloneable
        {
            #region Slice data members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
            public byte ret;

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
            public string idcode;

            #endregion

            partial void ice_initialize();

            #region Constructors

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
            public RLResultRes()
            {
                this.idcode = "";
                ice_initialize();
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
            public RLResultRes(byte ret, string idcode)
            {
                this.ret = ret;
                this.idcode = idcode;
                ice_initialize();
            }

            #endregion

            #region ICloneable members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
            public object Clone()
            {
                return MemberwiseClone();
            }

            #endregion

            #region Object members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
            public override int GetHashCode()
            {
                int h_ = 5381;
                IceInternal.HashUtil.hashAdd(ref h_, "::Sample::Protocol::RLResultRes");
                IceInternal.HashUtil.hashAdd(ref h_, ret);
                IceInternal.HashUtil.hashAdd(ref h_, idcode);
                return h_;
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
            public override bool Equals(object other)
            {
                if(object.ReferenceEquals(this, other))
                {
                    return true;
                }
                if(other == null)
                {
                    return false;
                }
                if(GetType() != other.GetType())
                {
                    return false;
                }
                RLResultRes o = (RLResultRes)other;
                if(!this.ret.Equals(o.ret))
                {
                    return false;
                }
                if(this.idcode == null)
                {
                    if(o.idcode != null)
                    {
                        return false;
                    }
                }
                else
                {
                    if(!this.idcode.Equals(o.idcode))
                    {
                        return false;
                    }
                }
                return true;
            }

            #endregion

            #region Comparison members

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
            public static bool operator==(RLResultRes lhs, RLResultRes rhs)
            {
                return Equals(lhs, rhs);
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
            public static bool operator!=(RLResultRes lhs, RLResultRes rhs)
            {
                return !Equals(lhs, rhs);
            }

            #endregion

            #region Marshaling support

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
            public void ice_writeMembers(Ice.OutputStream ostr)
            {
                ostr.writeByte(this.ret);
                ostr.writeString(this.idcode);
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
            public void ice_readMembers(Ice.InputStream istr)
            {
                this.ret = istr.readByte();
                this.idcode = istr.readString();
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
            public static void ice_write(Ice.OutputStream ostr, RLResultRes v)
            {
                if(v == null)
                {
                    _nullMarshalValue.ice_writeMembers(ostr);
                }
                else
                {
                    v.ice_writeMembers(ostr);
                }
            }

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
            public static RLResultRes ice_read(Ice.InputStream istr)
            {
                var v = new RLResultRes();
                v.ice_readMembers(istr);
                return v;
            }

            private static readonly RLResultRes _nullMarshalValue = new RLResultRes();

            #endregion
        }

        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1704")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1707")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1709")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1710")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1711")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1715")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1716")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1720")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1722")]
        [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Naming", "CA1724")]
        public partial interface IPlayerCo : Ice.Object, IPlayerCoOperations_
        {
        }
    }
}

namespace Sample
{
    namespace Protocol
    {
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
        public delegate void Callback_IPlayerCo_RegOrLoginReq(RLResultRes ret);

        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
        public delegate void Callback_IPlayerCo_JoinSceneReq(bool ret);
    }
}

namespace Sample
{
    namespace Protocol
    {
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
        public interface IPlayerCoPrx : Ice.ObjectPrx
        {
            RLResultRes RegOrLoginReq(string account, string pwd, Ice.OptionalContext context = new Ice.OptionalContext());

            _System.Threading.Tasks.Task<RLResultRes> RegOrLoginReqAsync(string account, string pwd, Ice.OptionalContext context = new Ice.OptionalContext(), _System.IProgress<bool> progress = null, _System.Threading.CancellationToken cancel = new _System.Threading.CancellationToken());

            Ice.AsyncResult<Callback_IPlayerCo_RegOrLoginReq> begin_RegOrLoginReq(string account, string pwd, Ice.OptionalContext context = new Ice.OptionalContext());

            Ice.AsyncResult begin_RegOrLoginReq(string account, string pwd, Ice.AsyncCallback callback, object cookie);

            Ice.AsyncResult begin_RegOrLoginReq(string account, string pwd, Ice.OptionalContext context, Ice.AsyncCallback callback, object cookie);

            RLResultRes end_RegOrLoginReq(Ice.AsyncResult asyncResult);

            bool JoinSceneReq(byte sceneid, Ice.OptionalContext context = new Ice.OptionalContext());

            _System.Threading.Tasks.Task<bool> JoinSceneReqAsync(byte sceneid, Ice.OptionalContext context = new Ice.OptionalContext(), _System.IProgress<bool> progress = null, _System.Threading.CancellationToken cancel = new _System.Threading.CancellationToken());

            Ice.AsyncResult<Callback_IPlayerCo_JoinSceneReq> begin_JoinSceneReq(byte sceneid, Ice.OptionalContext context = new Ice.OptionalContext());

            Ice.AsyncResult begin_JoinSceneReq(byte sceneid, Ice.AsyncCallback callback, object cookie);

            Ice.AsyncResult begin_JoinSceneReq(byte sceneid, Ice.OptionalContext context, Ice.AsyncCallback callback, object cookie);

            bool end_JoinSceneReq(Ice.AsyncResult asyncResult);
        }
    }
}

namespace Sample
{
    namespace Protocol
    {
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
        public interface IPlayerCoOperations_
        {
            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
            _System.Threading.Tasks.Task<RLResultRes> RegOrLoginReqAsync(string account, string pwd, Ice.Current current = null);

            [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
            _System.Threading.Tasks.Task<bool> JoinSceneReqAsync(byte sceneid, Ice.Current current = null);
        }
    }
}

namespace Sample
{
    namespace Protocol
    {
        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
        [_System.Serializable]
        public sealed class IPlayerCoPrxHelper : Ice.ObjectPrxHelperBase, IPlayerCoPrx
        {
            public IPlayerCoPrxHelper()
            {
            }

            public IPlayerCoPrxHelper(_System.Runtime.Serialization.SerializationInfo info, _System.Runtime.Serialization.StreamingContext context) : base(info, context)
            {
            }

            #region Synchronous operations

            public bool JoinSceneReq(byte sceneid, Ice.OptionalContext context = new Ice.OptionalContext())
            {
                try
                {
                    return _iceI_JoinSceneReqAsync(sceneid, context, null, _System.Threading.CancellationToken.None, true).Result;
                }
                catch(_System.AggregateException ex_)
                {
                    throw ex_.InnerException;
                }
            }

            public RLResultRes RegOrLoginReq(string account, string pwd, Ice.OptionalContext context = new Ice.OptionalContext())
            {
                try
                {
                    return _iceI_RegOrLoginReqAsync(account, pwd, context, null, _System.Threading.CancellationToken.None, true).Result;
                }
                catch(_System.AggregateException ex_)
                {
                    throw ex_.InnerException;
                }
            }

            #endregion

            #region Async Task operations

            public _System.Threading.Tasks.Task<bool> JoinSceneReqAsync(byte sceneid, Ice.OptionalContext context = new Ice.OptionalContext(), _System.IProgress<bool> progress = null, _System.Threading.CancellationToken cancel = new _System.Threading.CancellationToken())
            {
                return _iceI_JoinSceneReqAsync(sceneid, context, progress, cancel, false);
            }

            private _System.Threading.Tasks.Task<bool> _iceI_JoinSceneReqAsync(byte iceP_sceneid, Ice.OptionalContext context, _System.IProgress<bool> progress, _System.Threading.CancellationToken cancel, bool synchronous)
            {
                iceCheckTwowayOnly(_JoinSceneReq_name);
                var completed = new IceInternal.OperationTaskCompletionCallback<bool>(progress, cancel);
                _iceI_JoinSceneReq(iceP_sceneid, context, synchronous, completed);
                return completed.Task;
            }

            private const string _JoinSceneReq_name = "JoinSceneReq";

            private void _iceI_JoinSceneReq(byte iceP_sceneid, _System.Collections.Generic.Dictionary<string, string> context, bool synchronous, IceInternal.OutgoingAsyncCompletionCallback completed)
            {
                var outAsync = getOutgoingAsync<bool>(completed);
                outAsync.invoke(
                    _JoinSceneReq_name,
                    Ice.OperationMode.Normal,
                    Ice.FormatType.DefaultFormat,
                    context,
                    synchronous,
                    write: (Ice.OutputStream ostr) =>
                    {
                        ostr.writeByte(iceP_sceneid);
                    },
                    read: (Ice.InputStream istr) =>
                    {
                        bool ret;
                        ret = istr.readBool();
                        return ret;
                    });
            }

            public _System.Threading.Tasks.Task<RLResultRes> RegOrLoginReqAsync(string account, string pwd, Ice.OptionalContext context = new Ice.OptionalContext(), _System.IProgress<bool> progress = null, _System.Threading.CancellationToken cancel = new _System.Threading.CancellationToken())
            {
                return _iceI_RegOrLoginReqAsync(account, pwd, context, progress, cancel, false);
            }

            private _System.Threading.Tasks.Task<RLResultRes> _iceI_RegOrLoginReqAsync(string iceP_account, string iceP_pwd, Ice.OptionalContext context, _System.IProgress<bool> progress, _System.Threading.CancellationToken cancel, bool synchronous)
            {
                iceCheckTwowayOnly(_RegOrLoginReq_name);
                var completed = new IceInternal.OperationTaskCompletionCallback<RLResultRes>(progress, cancel);
                _iceI_RegOrLoginReq(iceP_account, iceP_pwd, context, synchronous, completed);
                return completed.Task;
            }

            private const string _RegOrLoginReq_name = "RegOrLoginReq";

            private void _iceI_RegOrLoginReq(string iceP_account, string iceP_pwd, _System.Collections.Generic.Dictionary<string, string> context, bool synchronous, IceInternal.OutgoingAsyncCompletionCallback completed)
            {
                var outAsync = getOutgoingAsync<RLResultRes>(completed);
                outAsync.invoke(
                    _RegOrLoginReq_name,
                    Ice.OperationMode.Normal,
                    Ice.FormatType.DefaultFormat,
                    context,
                    synchronous,
                    write: (Ice.OutputStream ostr) =>
                    {
                        ostr.writeString(iceP_account);
                        ostr.writeString(iceP_pwd);
                    },
                    read: (Ice.InputStream istr) =>
                    {
                        RLResultRes ret = null;
                        ret = RLResultRes.ice_read(istr);
                        return ret;
                    });
            }

            #endregion

            #region Asynchronous operations

            public Ice.AsyncResult<Callback_IPlayerCo_JoinSceneReq> begin_JoinSceneReq(byte sceneid, Ice.OptionalContext context = new Ice.OptionalContext())
            {
                return begin_JoinSceneReq(sceneid, context, null, null, false);
            }

            public Ice.AsyncResult begin_JoinSceneReq(byte sceneid, Ice.AsyncCallback callback, object cookie)
            {
                return begin_JoinSceneReq(sceneid, new Ice.OptionalContext(), callback, cookie, false);
            }

            public Ice.AsyncResult begin_JoinSceneReq(byte sceneid, Ice.OptionalContext context, Ice.AsyncCallback callback, object cookie)
            {
                return begin_JoinSceneReq(sceneid, context, callback, cookie, false);
            }

            public bool end_JoinSceneReq(Ice.AsyncResult asyncResult)
            {
                var resultI_ = IceInternal.AsyncResultI.check(asyncResult, this, _JoinSceneReq_name);
                var outgoing_ = (IceInternal.OutgoingAsyncT<bool>)resultI_.OutgoingAsync;
                return outgoing_.getResult(resultI_.wait());
            }

            private Ice.AsyncResult<Callback_IPlayerCo_JoinSceneReq> begin_JoinSceneReq(byte iceP_sceneid, _System.Collections.Generic.Dictionary<string, string> context, Ice.AsyncCallback completedCallback, object cookie, bool synchronous)
            {
                iceCheckAsyncTwowayOnly(_JoinSceneReq_name);
                var completed = new IceInternal.OperationAsyncResultCompletionCallback<Callback_IPlayerCo_JoinSceneReq, bool>(
                    (Callback_IPlayerCo_JoinSceneReq cb, bool ret) =>
                    {
                        if(cb != null)
                        {
                            cb.Invoke(ret);
                        }
                    },
                    this, _JoinSceneReq_name, cookie, completedCallback);
                _iceI_JoinSceneReq(iceP_sceneid, context, synchronous, completed);
                return completed;
            }

            public Ice.AsyncResult<Callback_IPlayerCo_RegOrLoginReq> begin_RegOrLoginReq(string account, string pwd, Ice.OptionalContext context = new Ice.OptionalContext())
            {
                return begin_RegOrLoginReq(account, pwd, context, null, null, false);
            }

            public Ice.AsyncResult begin_RegOrLoginReq(string account, string pwd, Ice.AsyncCallback callback, object cookie)
            {
                return begin_RegOrLoginReq(account, pwd, new Ice.OptionalContext(), callback, cookie, false);
            }

            public Ice.AsyncResult begin_RegOrLoginReq(string account, string pwd, Ice.OptionalContext context, Ice.AsyncCallback callback, object cookie)
            {
                return begin_RegOrLoginReq(account, pwd, context, callback, cookie, false);
            }

            public RLResultRes end_RegOrLoginReq(Ice.AsyncResult asyncResult)
            {
                var resultI_ = IceInternal.AsyncResultI.check(asyncResult, this, _RegOrLoginReq_name);
                var outgoing_ = (IceInternal.OutgoingAsyncT<RLResultRes>)resultI_.OutgoingAsync;
                return outgoing_.getResult(resultI_.wait());
            }

            private Ice.AsyncResult<Callback_IPlayerCo_RegOrLoginReq> begin_RegOrLoginReq(string iceP_account, string iceP_pwd, _System.Collections.Generic.Dictionary<string, string> context, Ice.AsyncCallback completedCallback, object cookie, bool synchronous)
            {
                iceCheckAsyncTwowayOnly(_RegOrLoginReq_name);
                var completed = new IceInternal.OperationAsyncResultCompletionCallback<Callback_IPlayerCo_RegOrLoginReq, RLResultRes>(
                    (Callback_IPlayerCo_RegOrLoginReq cb, RLResultRes ret) =>
                    {
                        if(cb != null)
                        {
                            cb.Invoke(ret);
                        }
                    },
                    this, _RegOrLoginReq_name, cookie, completedCallback);
                _iceI_RegOrLoginReq(iceP_account, iceP_pwd, context, synchronous, completed);
                return completed;
            }

            #endregion

            #region Checked and unchecked cast operations

            public static IPlayerCoPrx checkedCast(Ice.ObjectPrx b)
            {
                if(b == null)
                {
                    return null;
                }
                IPlayerCoPrx r = b as IPlayerCoPrx;
                if((r == null) && b.ice_isA(ice_staticId()))
                {
                    IPlayerCoPrxHelper h = new IPlayerCoPrxHelper();
                    h.iceCopyFrom(b);
                    r = h;
                }
                return r;
            }

            public static IPlayerCoPrx checkedCast(Ice.ObjectPrx b, _System.Collections.Generic.Dictionary<string, string> ctx)
            {
                if(b == null)
                {
                    return null;
                }
                IPlayerCoPrx r = b as IPlayerCoPrx;
                if((r == null) && b.ice_isA(ice_staticId(), ctx))
                {
                    IPlayerCoPrxHelper h = new IPlayerCoPrxHelper();
                    h.iceCopyFrom(b);
                    r = h;
                }
                return r;
            }

            public static IPlayerCoPrx checkedCast(Ice.ObjectPrx b, string f)
            {
                if(b == null)
                {
                    return null;
                }
                Ice.ObjectPrx bb = b.ice_facet(f);
                try
                {
                    if(bb.ice_isA(ice_staticId()))
                    {
                        IPlayerCoPrxHelper h = new IPlayerCoPrxHelper();
                        h.iceCopyFrom(bb);
                        return h;
                    }
                }
                catch(Ice.FacetNotExistException)
                {
                }
                return null;
            }

            public static IPlayerCoPrx checkedCast(Ice.ObjectPrx b, string f, _System.Collections.Generic.Dictionary<string, string> ctx)
            {
                if(b == null)
                {
                    return null;
                }
                Ice.ObjectPrx bb = b.ice_facet(f);
                try
                {
                    if(bb.ice_isA(ice_staticId(), ctx))
                    {
                        IPlayerCoPrxHelper h = new IPlayerCoPrxHelper();
                        h.iceCopyFrom(bb);
                        return h;
                    }
                }
                catch(Ice.FacetNotExistException)
                {
                }
                return null;
            }

            public static IPlayerCoPrx uncheckedCast(Ice.ObjectPrx b)
            {
                if(b == null)
                {
                    return null;
                }
                IPlayerCoPrx r = b as IPlayerCoPrx;
                if(r == null)
                {
                    IPlayerCoPrxHelper h = new IPlayerCoPrxHelper();
                    h.iceCopyFrom(b);
                    r = h;
                }
                return r;
            }

            public static IPlayerCoPrx uncheckedCast(Ice.ObjectPrx b, string f)
            {
                if(b == null)
                {
                    return null;
                }
                Ice.ObjectPrx bb = b.ice_facet(f);
                IPlayerCoPrxHelper h = new IPlayerCoPrxHelper();
                h.iceCopyFrom(bb);
                return h;
            }

            private static readonly string[] _ids =
            {
                "::Ice::Object",
                "::Sample::Protocol::IPlayerCo"
            };

            public static string ice_staticId()
            {
                return _ids[1];
            }

            #endregion

            #region Marshaling support

            public static void write(Ice.OutputStream ostr, IPlayerCoPrx v)
            {
                ostr.writeProxy(v);
            }

            public static IPlayerCoPrx read(Ice.InputStream istr)
            {
                Ice.ObjectPrx proxy = istr.readProxy();
                if(proxy != null)
                {
                    IPlayerCoPrxHelper result = new IPlayerCoPrxHelper();
                    result.iceCopyFrom(proxy);
                    return result;
                }
                return null;
            }

            #endregion
        }
    }
}

namespace Sample
{
    namespace Protocol
    {
        [_System.Runtime.InteropServices.ComVisible(false)]
        [_System.CodeDom.Compiler.GeneratedCodeAttribute("slice2cs", "3.7.1")]
        public abstract class IPlayerCoDisp_ : Ice.ObjectImpl, IPlayerCo
        {
            #region Slice operations

            public abstract _System.Threading.Tasks.Task<RLResultRes> RegOrLoginReqAsync(string account, string pwd, Ice.Current current = null);

            public abstract _System.Threading.Tasks.Task<bool> JoinSceneReqAsync(byte sceneid, Ice.Current current = null);

            #endregion

            #region Slice type-related members

            private static readonly string[] _ids =
            {
                "::Ice::Object",
                "::Sample::Protocol::IPlayerCo"
            };

            public override bool ice_isA(string s, Ice.Current current = null)
            {
                return _System.Array.BinarySearch(_ids, s, IceUtilInternal.StringUtil.OrdinalStringComparer) >= 0;
            }

            public override string[] ice_ids(Ice.Current current = null)
            {
                return _ids;
            }

            public override string ice_id(Ice.Current current = null)
            {
                return _ids[1];
            }

            public static new string ice_staticId()
            {
                return _ids[1];
            }

            #endregion

            #region Operation dispatch

            [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
            public static _System.Threading.Tasks.Task<Ice.OutputStream>
            iceD_RegOrLoginReq(IPlayerCo obj, IceInternal.Incoming inS, Ice.Current current)
            {
                Ice.ObjectImpl.iceCheckMode(Ice.OperationMode.Normal, current.mode);
                var istr = inS.startReadParams();
                string iceP_account;
                string iceP_pwd;
                iceP_account = istr.readString();
                iceP_pwd = istr.readString();
                inS.endReadParams();
                return inS.setResultTask<RLResultRes>(obj.RegOrLoginReqAsync(iceP_account, iceP_pwd, current),
                    (ostr, ret) =>
                    {
                        RLResultRes.ice_write(ostr, ret);
                    });
            }

            [_System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1011")]
            public static _System.Threading.Tasks.Task<Ice.OutputStream>
            iceD_JoinSceneReq(IPlayerCo obj, IceInternal.Incoming inS, Ice.Current current)
            {
                Ice.ObjectImpl.iceCheckMode(Ice.OperationMode.Normal, current.mode);
                var istr = inS.startReadParams();
                byte iceP_sceneid;
                iceP_sceneid = istr.readByte();
                inS.endReadParams();
                return inS.setResultTask<bool>(obj.JoinSceneReqAsync(iceP_sceneid, current),
                    (ostr, ret) =>
                    {
                        ostr.writeBool(ret);
                    });
            }

            private static readonly string[] _all =
            {
                "JoinSceneReq",
                "RegOrLoginReq",
                "ice_id",
                "ice_ids",
                "ice_isA",
                "ice_ping"
            };

            public override _System.Threading.Tasks.Task<Ice.OutputStream>
            iceDispatch(IceInternal.Incoming inS, Ice.Current current)
            {
                int pos = _System.Array.BinarySearch(_all, current.operation, IceUtilInternal.StringUtil.OrdinalStringComparer);
                if(pos < 0)
                {
                    throw new Ice.OperationNotExistException(current.id, current.facet, current.operation);
                }

                switch(pos)
                {
                    case 0:
                    {
                        return iceD_JoinSceneReq(this, inS, current);
                    }
                    case 1:
                    {
                        return iceD_RegOrLoginReq(this, inS, current);
                    }
                    case 2:
                    {
                        return Ice.ObjectImpl.iceD_ice_id(this, inS, current);
                    }
                    case 3:
                    {
                        return Ice.ObjectImpl.iceD_ice_ids(this, inS, current);
                    }
                    case 4:
                    {
                        return Ice.ObjectImpl.iceD_ice_isA(this, inS, current);
                    }
                    case 5:
                    {
                        return Ice.ObjectImpl.iceD_ice_ping(this, inS, current);
                    }
                }

                _System.Diagnostics.Debug.Assert(false);
                throw new Ice.OperationNotExistException(current.id, current.facet, current.operation);
            }

            #endregion
        }
    }
}
